packages:
  - apps/*
  - packages/*

overrides:
  cookie@<0.7.0: '>=0.7.0'
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.3.7 <10.5.0: '>=10.5.0'
  js-yaml@<3.14.2: '>=3.14.2'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
  send@<0.19.0: '>=0.19.0'
